server:
  port: 8888 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: nacos-provider # 路由id，全局唯一
          uri: lb://nacos-provider # 路由目的地
          predicates: # 路由断言，符合断言条件才会跳转到路由目的地
            - Path=/echo/** # 请求路径断言
          filters: # 路由过滤器，对请求和响应做处理
            - AddResponseHeader=X-Response-Special, Special # 当前路由专用过滤器
      default-filters:
        - AddResponseHeader=X-Response-Default, Default # 默认过滤器